### ISSUE TITLE
Code mistake in Experimental

### ISSUE THREAD

**Issue by c0d3rman** [thalmiclabs/myo.js#16]
In the [experimental readme](https://github.com/thalmiclabs/myo.js/blob/master/experimental/README.md), the example for Myo Tap has `myMyo.unlock()` when it should have `myMyo.lock()`. It is currently

``` javascript
//Myo tap to lock and unlock!
myMyo.on('myo_tap', function(){
    if(myMyo.isLocked){
        myMyo.unlock();
    }else{
        myMyo.unlock();
    }
});
```

when it should be

``` javascript
//Myo tap to lock and unlock!
myMyo.on('myo_tap', function(){
    if(myMyo.isLocked){
        myMyo.unlock();
    }else{
        myMyo.lock();
    }
});
```

Also toggling the lock state is common enough that you might want to add a function to do it (to prevent mistakes like these.)

**Comment by stolksdorf** [comment]
Good call! Thanks for the headsup.

Myo.js is a bit behind how the current SDK handles locking. I haven't had time to update it yet. But when I do I'll keep your suggestion in mind!

**Comment by stolksdorf** [comment]
Thanks for the heads up! Fixed.

Myo.js is behind the SDK right now in terms of how it does locking policy. I just haven't had time to update it. I'll keep your suggestion in mind when I do though!
