### ISSUE TITLE
Connecting Myo with Myo Connect ?

### ISSUE THREAD

**Issue by onuralpszr** [thalmiclabs/myo.js#17]
Hello  ; Can we use "Myo" without using Myo Connect ? can it be independent ?

**Comment by stolksdorf** [comment]
Unfortunately no. Myo Connect does all the communication with the Myo and emits events over web sockets. Myo.js listens for these events and easily allows the developer to interact with the Myo using Myo Connect.

**Comment by onuralpszr** [comment]
Thank you
