### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mpf82** [thalmiclabs/myo.js#20]
Hello,

package.json states that the code is licensed under ISC.

However, the LICENSE.txt looks like a BSD 3-clause license.

The README states "The Myo.js project is licensed using the modified BSD license" - which would fit both ISC and BSD3.

Could you please clarify which license is used and please fix either the package.json or the LICENSE.txt?

**Comment by stolksdorf** [comment]
Thanks for the headsup mpf82! Myo.js is licensed under **BSD-3** as the License.txt says. The `package.json` was wrong and I just pushed v2.1.1 that corrects this.
