### ISSUE TITLE
Only trigger pose events from 'rest' state?

### ISSUE THREAD

**Issue by bombarie** [thalmiclabs/myo.js#3]
Is it possible to configure the myo lib to only trigger a pose event from the rest state? I'm having issues were during a sustained fingers_spread suddenly a wave_out is detected after which the fingers_spread off event won't be sent when I go back to the rest pose. I'll then have trigger fingers_spread again and release (without any other poses interfering) in order to catch the fingers_spread off event. How to prevent this from happening?

**Comment by smngreenberg** [comment]
Normally the transitions between gestures should always go through rest (even very quickly) so I'm a bit surprised by this. 

In the case you outlined you should be getting events with edge=false before the wave out is detected at all. Do you have some reproducing code I could take a look at?

**Comment by bombarie** [comment]
I put it into a gist for you: https://gist.github.com/bombarie/19a534603c403f220530.
I cleaned out the rudimentary logic I was executing, now it's just console logs when the poses' edge property are true or false. There's a setInterval that keeps the Myo from locking while a fist or fingers_spread is true. When I spread my fingers and slowly move my hand outward, I can see wave_out triggering true before fingers_spread has gone to false. Hope you can reproduce.

Here's the console output I got:

```
> node ./bin/www

myo connected
fingers_spread ON        <-- here I'm just testing on/off triggers a few times
fingers_spread OFF
locked
fingers_spread ON
unlocked
fingers_spread OFF
wave_out ON
fingers_spread ON         <-- here's where I flex my fingers continuously, moving my hand outward
wave_out ON              <-- wave_out emits true.. shouldn't fingers_spread have emitted false?
fingers_spread ON         <-- moved hand back to center... fingers_spread emits true again (??)
fingers_spread OFF
fingers_spread ON
fingers_spread OFF
```

**Comment by smngreenberg** [comment]
I stand corrected, thanks for the gist. I'm looking into a fix now. 

Note that even if/when this gets fixed, it's still possible that you may not receive the OFF events if the Myo becomes locked in the middle of holding a gesture.

**Comment by bombarie** [comment]
Thanks for looking into it! As for the myo locking, yes I understand that. Would be annoying if OFF-events would be triggered if it goes to lock. It's more prudent to know that as long as the one pose is detected, another can't trigger. Is there a way to poll the current edge state of the various poses in the library?

**Comment by smngreenberg** [comment]
The pull request has been merged so this should be fixed if you download the latest. 

Conceptually thinking, polling the edge state doesn't sound like it would be very useful. The pose is either active or not and the transition between those two states (the edge) is a fraction of a second, making it much easier to track the pose states themselves. Unless of course I'm misunderstanding your question. If that's the case, feel free to put in another issue. :)
